- job:
    name: designate-base
    parent: devstack-tempest
    post-run: playbooks/designate-base/post.yaml
    vars:
      devstack_localrc:
        DESIGNATE_SERVICE_PORT_DNS: 5322
        TEMPEST_PLUGINS: /opt/stack/designate-tempest-plugin
      devstack_plugins:
        designate: https://opendev.org/openstack/designate
      devstack_services:
        designate: true
      tox_envlist: all
      tempest_test_regex: |
        designate_tempest_plugin.*
    required-projects:
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$

- job:
    name: designate-bind9
    parent: designate-base

- job:
    name: designate-bind9-manager-model
    parent: designate-bind9
    vars:
      devstack_services:
        designate-worker: false
        designate-producer: false
        designate-pool-manager: true
        designate-zone-manager: true

- job:
    name: designate-bind9-py36
    parent: designate-bind9
    vars:
      devstack_localrc:
        USE_PYTHON3: true
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-bak: false

- job:
    name: designate-devstack-base
    parent: legacy-dsvm-base
    vars:
      database: mysql
      python_version: py27
      identity_v3_only: 0
      manager_model: 0
      backend: pdns4
    required-projects:
      - openstack/devstack-gate
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
      - openstack/tempest
    run: playbooks/legacy/designate-devstack-base/run.yaml
    post-run: playbooks/legacy/designate-devstack-base/post.yaml
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$

- job:
    name: designate-devstack-agent-base
    parent: legacy-dsvm-base
    required-projects:
      - openstack/devstack-gate
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
      - openstack/tempest
    run: playbooks/legacy/designate-devstack-agent-base/run.yaml
    post-run: playbooks/legacy/designate-devstack-agent-base/post.yaml
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$

- job:
    name: designate-grenade-pdns4
    parent: legacy-dsvm-base
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
    run: playbooks/legacy/grenade-devstack-designate-pdns4/run.yaml
    post-run: playbooks/legacy/grenade-devstack-designate-pdns4/post.yaml
    timeout: 10800
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$

- job:
    name: designate-devstack-agent-djbdns
    parent: designate-devstack-agent-base
    vars:
      backend_driver: djbdns

- job:
    name: designate-devstack-agent-gdnsd
    parent: designate-devstack-agent-base
    vars:
      backend_driver: gdnsd

- job:
    name: designate-devstack-agent-knot2
    parent: designate-devstack-agent-base
    vars:
      backend_driver: knot2

- job:
    name: designate-devstack-pdns4
    parent: designate-devstack-base
    vars:
      backend: pdns4

- job:
    name: designate-devstack-pdns4-postgres
    parent: designate-devstack-base
    vars:
      backend: pdns4
      database: postgres

- project-template:
    name: designate-devstack-jobs
    check:
      jobs:
        - designate-bind9
        - designate-bind9-manager-model
        - designate-bind9-py36
        - designate-devstack-pdns4
        - designate-devstack-pdns4-postgres
        - designate-grenade-pdns4
    gate:
      queue: designate
      jobs:
        - designate-bind9
        - designate-bind9-manager-model
        - designate-bind9-py36
        - designate-devstack-pdns4
        - designate-devstack-pdns4-postgres
        - designate-grenade-pdns4
    experimental:
      jobs:
        - designate-devstack-agent-knot2
        - designate-devstack-agent-djbdns
        - designate-devstack-agent-gdnsd

- project:
    templates:
      - designate-devstack-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-tempest-plugin-designate-scenario-stein
    gate:
      queue: designate
